### ISSUE TITLE
Some videos stop Utuputki and show only a black image

### ISSUE THREAD

**Issue by tuomosipola** [turol/utuputki#13]
Some videos stop Utuputki and show only a black image. 

It does not progress and only shows a blank screen. 

Once users skipped the videos, normal operations continued.

On 2019-10-12 one of these two videos stopped it:
https://www.youtube.com/watch?v=6exXWnz9CWY
https://www.youtube.com/watch?v=O6hXjxQ0_lk

**Comment by turol** [comment]
Also broken:
https://www.youtube.com/watch?v=ikYZ5iGalLE

**Comment by turol** [comment]
Look like a VLC/raspberry pi decoder issue. Something to do with MP4 subformats.

**Comment by turol** [comment]
Works now with Raspberry Pi 4, newer Raspbian and newer VLC.
